# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tmYLrH2TVkjyWRfLGMEIMpigejz0z_ll
"""

import re

def valid_number_or_not(number):

    pattern = r'^(\+?\d{1,3}[-.\s]?)?(\(\d{1,4}\)|\d{1,4})[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,4}$'


    # Use re.match to check if the number matches the pattern
    if re.match(pattern, number):
        return True
    else:
        return False

# Input from the user for the number_to_check variable
number_to_check = input("Enter a contact number: ")

if valid_number_or_not(number_to_check):
    print(f"{number_to_check} is a valid contact number.")
else:
    print(f"{number_to_check} is an invalid contact number.")